version: '2'
services:
    django_main:
      build: .
      container_name : django_main
      command:  python3 manage.py runserver 0.0.0.0:8000
      volumes:    
        - ./code:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

    db:   
      image: mysql
      container_name: db
      expose:
        - "3306"
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=shuping
        - MYSQL_ROOT_PASSWORD=lidaxiang
   